# Generated by Django 6.0.1 on 2026-02-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Brand', 'verbose_name_plural': '5. Brands'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-year', 'order'], 'verbose_name': 'Gallery Item', 'verbose_name_plural': '6. Galleries'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': '4. Products'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Sector', 'verbose_name_plural': '1. Sectors'},
        ),
        migrations.AlterModelOptions(
            name='venture',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Venture', 'verbose_name_plural': '2. Ventures'},
        ),
        migrations.AlterModelOptions(
            name='venturedetail',
            options={'ordering': ['order'], 'verbose_name': 'Venture Detail', 'verbose_name_plural': '3. Venture Details'},
        ),
    ]
