# Generated by Django 6.0.1 on 2026-02-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0002_alter_brand_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
