# Generated by Django 6.0.1 on 2026-04-14 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0003_brand_description_gallery_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venture',
            name='working_area_map',
            field=models.ImageField(blank=True, null=True, upload_to='ventures/maps/'),
        ),
        migrations.CreateModel(
            name='WorkingDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_operational', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='ventures.venture')),
            ],
            options={
                'verbose_name': 'Working District',
                'verbose_name_plural': '7. Working Districts',
                'ordering': ['order', 'name'],
            },
        ),
    ]
