# Generated by Django 6.0.1 on 2026-04-14 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0004_venture_working_area_map_workingdistrict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venture',
            name='working_area_map',
        ),
        migrations.CreateModel(
            name='AreaMapImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='area_maps/')),
                ('alt_text', models.CharField(blank=True, default='Area of Working', max_length=200)),
                ('venture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='area_map', to='ventures.venture')),
            ],
            options={
                'verbose_name': 'Area Map Image',
                'verbose_name_plural': '8. Area Map Images',
            },
        ),
        migrations.CreateModel(
            name='AreaOfWorking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=200)),
                ('is_operational', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='ventures.venture')),
            ],
            options={
                'verbose_name': 'Area of Working',
                'verbose_name_plural': '7. Areas of Working',
                'ordering': ['order', 'district_name'],
            },
        ),
        migrations.DeleteModel(
            name='WorkingDistrict',
        ),
    ]
