# Generated by Django 6.0.1 on 2026-04-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0005_remove_venture_working_area_map_areamapimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areamapimage',
            name='image',
            field=models.ImageField(help_text='Upload Kerala map image (PNG recommended)', upload_to='area_maps/'),
        ),
        migrations.AlterField(
            model_name='areaofworking',
            name='district_name',
            field=models.CharField(choices=[('Kasaragod', 'Kasaragod'), ('Kannur', 'Kannur'), ('Wayanad', 'Wayanad'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Thrissur', 'Thrissur'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kottayam', 'Kottayam'), ('Alappuzha', 'Alappuzha'), ('Pathanamthitta', 'Pathanamthitta'), ('Kollam', 'Kollam'), ('Thiruvananthapuram', 'Thiruvananthapuram')], help_text='Select a Kerala district', max_length=200),
        ),
        migrations.AlterField(
            model_name='areaofworking',
            name='is_operational',
            field=models.BooleanField(default=True, help_text='Uncheck to mark this district as inactive'),
        ),
        migrations.AlterUniqueTogether(
            name='areaofworking',
            unique_together={('venture', 'district_name')},
        ),
    ]
