# Generated by Django 6.0.1 on 2026-04-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0006_alter_areamapimage_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='areaofworking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='areaofworking',
            name='venture',
        ),
        migrations.DeleteModel(
            name='AreaMapImage',
        ),
        migrations.DeleteModel(
            name='AreaOfWorking',
        ),
    ]
