# Generated by Django 6.0.1 on 2026-04-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0007_alter_areaofworking_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('map_image', models.ImageField(blank=True, help_text='Map or area image displayed when this district is selected.', null=True, upload_to='districts/maps/')),
                ('is_operational', models.BooleanField(default=True, help_text='Toggle to mark district as active/inactive.')),
                ('order', models.IntegerField(default=0)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='ventures.venture')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': '7. Districts',
                'ordering': ['order', 'name'],
            },
        ),
    ]
