# Generated by Django 6.0.1 on 2026-04-16 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0008_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='venture',
            name='area_working_image',
            field=models.ImageField(blank=True, help_text="Single map / area image shown in the 'Area of Working' section.", null=True, upload_to='ventures/area_working/'),
        ),
        migrations.CreateModel(
            name='AreaOfWorking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='District / city / region name.', max_length=200)),
                ('is_operational', models.BooleanField(default=True, help_text='Mark this location as active or inactive.')),
                ('order', models.IntegerField(default=0)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_of_workings', to='ventures.venture')),
            ],
            options={
                'verbose_name': 'Area of Working',
                'verbose_name_plural': '7. Areas of Working',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
