# Generated by Django 6.0.1 on 2026-04-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0009_venture_area_working_image_areaofworking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofworking',
            name='is_operational',
            field=models.BooleanField(default=True, help_text='Active or inactive.'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='area_working_image',
            field=models.ImageField(blank=True, help_text='Single map image shown in the Area of Working section.', null=True, upload_to='ventures/area_working/'),
        ),
    ]
