# Generated by Django 6.0.1 on 2026-04-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0010_alter_areaofworking_is_operational_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofworking',
            name='is_operational',
            field=models.BooleanField(default=True, help_text='Mark as active or inactive.'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='area_working_image',
            field=models.ImageField(blank=True, help_text="Upload one map image for the 'Area of Working' section. This image is always displayed on the right panel.", null=True, upload_to='ventures/area_working/'),
        ),
    ]
