# Generated by Django 6.0.1 on 2026-04-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0011_alter_areaofworking_is_operational_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venture',
            name='area_working_image',
        ),
        migrations.DeleteModel(
            name='AreaOfWorking',
        ),
    ]
