# Generated by Django 6.0.1 on 2026-04-16 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0013_venture_area_working_image_areaofworking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venture',
            name='area_working_image',
        ),
        migrations.AddField(
            model_name='areaofworking',
            name='area_image',
            field=models.ImageField(blank=True, help_text='Map or area image displayed on the right panel when this area is selected.', null=True, upload_to='areas_of_working/'),
        ),
        migrations.AlterField(
            model_name='areaofworking',
            name='is_operational',
            field=models.BooleanField(default=True, help_text='Toggle to mark this area as active / inactive.'),
        ),
        migrations.AlterField(
            model_name='areaofworking',
            name='name',
            field=models.CharField(help_text='Area / district name shown in the left list.', max_length=200),
        ),
        migrations.AlterField(
            model_name='areaofworking',
            name='venture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_of_working', to='ventures.venture'),
        ),
    ]
