# Generated by Django 6.0.1 on 2026-05-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0014_remove_venture_area_working_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venturedetail',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Optional banner / feature image for this detail section.', null=True, upload_to='venture_details/'),
        ),
    ]
