# Generated by Django 6.0.1 on 2026-05-10 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0015_venturedetail_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venturedetail',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Optional banner image shown as a parallax hero strip on the detail page.', null=True, upload_to='venture_details/'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Feature text. Wrap keywords in &lt;strong&gt; for bold, e.g. "Reliable <strong>B2B distribution</strong> with optimized delivery schedules"', max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ventures.venture')),
            ],
            options={
                'verbose_name': 'Product Feature',
                'verbose_name_plural': '8. Product Features',
                'ordering': ['order'],
            },
        ),
    ]
