# Generated by Django 6.0.1 on 2026-05-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0016_alter_venturedetail_banner_image_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='venture',
            name='about_description',
            field=models.TextField(blank=True, help_text='Body text shown beneath the about title in the det-box section.'),
        ),
        migrations.AddField(
            model_name='venture',
            name='about_title',
            field=models.CharField(blank=True, help_text="Heading shown in the 'About this Venture' det-box section.", max_length=300),
        ),
    ]
