# Generated by Django 6.0.1 on 2026-05-10 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0017_venture_about_description_venture_about_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofworking',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Area of Working', 'verbose_name_plural': '8. Areas of Working'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Brand', 'verbose_name_plural': '6. Brands'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['order'], 'verbose_name': 'Product Feature', 'verbose_name_plural': '9. Product Features'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-year', 'order'], 'verbose_name': 'Gallery Item', 'verbose_name_plural': '7. Galleries'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': '5. Products'},
        ),
        migrations.AlterModelOptions(
            name='venturedetail',
            options={'ordering': ['order'], 'verbose_name': 'Venture Detail', 'verbose_name_plural': '4. Venture Details'},
        ),
        migrations.RemoveField(
            model_name='venture',
            name='about_description',
        ),
        migrations.RemoveField(
            model_name='venture',
            name='about_title',
        ),
        migrations.CreateModel(
            name='VentureAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Heading shown inside the det-box section, e.g. 'B2B Centric Warehouse for 2 & 3 Wheeler Parts'.", max_length=300)),
                ('description', models.TextField(help_text='Body paragraph shown beneath the title in the det-box section.')),
                ('venture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='ventures.venture')),
            ],
            options={
                'verbose_name': 'Venture About',
                'verbose_name_plural': '3. Venture About',
            },
        ),
    ]
