# Generated by Django 6.0.1 on 2026-02-04 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year of the milestone', unique=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('label', models.CharField(help_text="Short label for the milestone (e.g., 'The Beginning')", max_length=100)),
                ('title', models.CharField(help_text='Main title for the milestone', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what happened this year')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this milestone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journey Milestone',
                'verbose_name_plural': 'Journey Milestones',
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the team member', max_length=100)),
                ('position', models.CharField(help_text='Job title/position', max_length=100)),
                ('position_type', models.CharField(choices=[('founder', 'Founder & Managing Director'), ('co_founder', 'Co-Founder & Director'), ('director', 'Director'), ('manager', 'Manager'), ('executive', 'Executive'), ('other', 'Other')], default='other', help_text='Position category', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short biography or description')),
                ('photo', models.ImageField(blank=True, help_text='Team member photo', null=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL (optional)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this team member')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
