# Generated by Django 6.0.1 on 2026-02-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand/Partner name', max_length=100)),
                ('logo', models.ImageField(help_text='Brand logo image', upload_to='brands/')),
                ('website_url', models.URLField(blank=True, help_text='Brand website URL (optional)')),
                ('description', models.TextField(blank=True, help_text='Brief description about the brand (optional)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this brand')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['order', 'name'],
            },
        ),
    ]
