# Generated by Django 6.0.1 on 2026-02-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['order'], 'verbose_name': 'Brand Logo', 'verbose_name_plural': 'Brand Logos'},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='website_url',
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show/Hide brand'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='Brand name (for admin reference only)', max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
    ]
