# Generated by Django 6.0.1 on 2026-02-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_careerapplication_careerpagecontent_jobrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerApplication',
        ),
        migrations.DeleteModel(
            name='CareerPageContent',
        ),
        migrations.DeleteModel(
            name='JobRole',
        ),
    ]
