# Generated by Django 6.0.1 on 2026-02-05 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_careerapplication_delete_careerpagecontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Applicant's full name", max_length=200)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('job_role', models.CharField(help_text='Applied job role', max_length=200)),
                ('message', models.TextField(blank=True, help_text='Cover letter or message')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='new', help_text='Application status', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True, help_text='Date of application')),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to applicant)')),
            ],
            options={
                'verbose_name': 'Career Application',
                'verbose_name_plural': 'Career Applications',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title/position', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Job description (optional)')),
                ('vacancy_count', models.PositiveIntegerField(default=1, help_text='Number of openings for this position')),
                ('image', models.ImageField(blank=True, help_text='Job thumbnail image (optional)', null=True, upload_to='jobs/')),
                ('posted_date', models.DateField(default=django.utils.timezone.now, help_text='Job posting date')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Show in dropdown and recent jobs')),
                ('show_in_recent', models.BooleanField(default=True, help_text="Show in 'Recent Jobs' sidebar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
                'ordering': ['order', '-posted_date'],
            },
        ),
    ]
