# Generated by Django 6.0.1 on 2026-02-06 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_careerapplication_jobrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('hq', 'Headquarters'), ('unit', 'Production Unit'), ('godown', 'Warehouse')], max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField()),
                ('icon', models.CharField(choices=[('🏢', 'Office Building'), ('🏭', 'Factory'), ('📦', 'Warehouse')], default='🏢', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MapConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#dc2626', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='main.maplocation')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='main.maplocation')),
            ],
            options={
                'unique_together': {('from_location', 'to_location')},
            },
        ),
    ]
