# Generated by Django 6.0.1 on 2026-05-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_maplocation_mapconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client name', max_length=100)),
                ('avatar', models.ImageField(blank=True, help_text='Client photo', null=True, upload_to='testimonials/')),
                ('content', models.TextField(help_text='Review / testimonial text')),
                ('social_link', models.URLField(blank=True, help_text='Social media post link (e.g. Facebook, Twitter, Instagram)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show / Hide')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
