# Generated by Django 6.0.1 on 2026-05-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='content',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='social_link',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='platform',
            field=models.CharField(choices=[('twitter', 'Via X-Twitter'), ('facebook', 'Via Facebook'), ('instagram', 'Via Instagram'), ('linkedin', 'Via LinkedIn'), ('google', 'Via Google'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='platform_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='review',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatar/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
