# Generated by Django 6.0.1 on 2026-06-24 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_testimonial_options_remove_testimonial_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Program title / name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description of the program (optional)')),
                ('image', models.ImageField(help_text='Program image', upload_to='programs/')),
                ('year', models.IntegerField(default=2026, help_text='Year the program took place', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this program')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Gallery',
                'verbose_name_plural': 'Program Gallery',
                'ordering': ['-year', 'order', 'title'],
            },
        ),
    ]
